### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ayadgroupe** [MBuchalik/cordova-plugin-ios-permissions#2] opened 2017-10-10 21:23 UTC
Hi! How can I contribute to this plugin who saved my app ?
I made the french translation how can I send it to you, to add it to the plugin ?

Thanks

**Comment by MBuchalik** [comment] 2017-10-11 07:07
I had a look at the plugin in your repo (which isn't a forked one btw). The problem is that you haven't added a src/ios/fr.lproj file. Instead, the words are hardcoded in the plugin.xml file. This cannot be merged correctly into this plugin (without breaking other features). So I would suggest:

1. Fork this plugin
2. Add a src/ios/fr.lproj file with the translations you made
3. Add ``` <resource-file src="src/ios/fr.lproj" />``` to the plugin.xml
4. Send me a pull request

Thanks for your contribution to this plugin! :smiley:

**Comment by ayadgroupe** [comment] 2017-10-11 07:25
Hi, I just did what you asked =) Hope it will be fine.
Happy to contribute ;)

**Comment by MBuchalik** [comment] 2017-10-11 07:59
Now, you only need to send a pull request so that I can merge the changes. 😃 See https://help.github.com/articles/creating-a-pull-request/

But before you send a pull request:
1. Have you tested your version of the plugin?
2. Make sure the indentation in the plugin.xml is correct - at the moment, it looks like this:
```xml
	<resource-file src="src/ios/de.lproj" />
<resource-file src="src/ios/fr.lproj" />
```

**Comment by MBuchalik** [comment] 2017-11-13 09:45
I am closing this issue since there was no activity within the last month. If you are still interested in sending a pull request, feel free to comment on this issue.

**Closed as completed by MBuchalik** 2017-11-13 09:45 UTC
